### ISSUE TITLE
Can't create new campaign and other some other nodes

### ISSUE THREAD

**Issue by bjarnef** [TeaCommerce/Tea-Commerce-for-Umbraco#43]
It seems there are issues in Umbraco 7.3.1 and Tea Commerce 3.0.7, when creating e.g. a new campaign:

![image](https://cloud.githubusercontent.com/assets/2919859/11430796/5a2fd908-948c-11e5-92a2-70fb10439e6b.png)

It also happens for other nodes likes countries, currencies, VAT groups, email templates ... :
![image](https://cloud.githubusercontent.com/assets/2919859/11430801/7ab258ea-948c-11e5-9711-32ae8beef8f9.png)

![image](https://cloud.githubusercontent.com/assets/2919859/11430810/aea08654-948c-11e5-8a8e-f08de3ddf6d0.png)

It is btw. using SQL CE ..  not sure if Tea Commerce still support it?

**Comment by bjarnef** [comment]
Ahh I get Log errors like this:

```
System.Data.SqlServerCe.SqlCeException (0x80004005): The specified table does not exist. [ TeaCommerce_Store ]
   at System.Data.SqlServerCe.SqlCeCommand.ProcessResults(Int32 hr)
   at System.Data.SqlServerCe.SqlCeCommand.CompileQueryPlan()
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at TeaCommerce.Api.Persistence.Database.<Query>d__c`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at TeaCommerce.Api.Persistence.Repositories.StoreRepository.GetInternal(String sql, Object[] args)
   at TeaCommerce.Api.Persistence.Repositories.StoreRepository.GetAll()
   at TeaCommerce.Api.Services.StoreService.GetCachedList()
   at TeaCommerce.Api.Services.StoreService.GetAll()
   at TeaCommerce.Umbraco.Install.PackageActions.GrantPermissions.Execute(String packageName, XmlNode xmlData)
   at umbraco.cms.businesslogic.packager.PackageAction.RunPackageAction(String packageName, String actionAlias, XmlNode actionXml)
```

**Comment by andersburla** [comment]
Can you see if the DB tables has been created in the SQL CE database?

**Comment by bjarnef** [comment]
Hi Anders

Yes, it was a SQL CE database - just a local install via WebMatrix.

**Comment by andersburla** [comment]
Just tried with the latest Tea Commerce version being build (3.2) and it works with SQL CE. Haven't tried older versions as this will be the new go to version :)
