### ISSUE TITLE
TC.GetVariantGroups<string>(1, product.Id.ToString()) Exception

### ISSUE THREAD

**Issue by NiklasRaab** [TeaCommerce/Tea-Commerce-for-Umbraco#56]
TC.GetVariantGroups<string>(1, product.Id.ToString());

throws: 
```
Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'TeaCommerce.Umbraco.Configuration.Variants.Services.IVariantService`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[TeaCommerce.Umbraco.Configuration.Variants.Models.VariantPublishedContent, TeaCommerce.Umbraco.Configuration, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]]' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   at TeaCommerce.Umbraco.Web.TC.GetVariants[T](Int64 storeId, T product, Boolean onlyValid) in C:\Users\niklas.raab\AppData\Local\JetBrains\Shared\v07\DecompilerCache\decompiler\2DBF3533-0880-4597-9E2C-62FFDD726AA9\ae\88000066\TC.cs:line 325
   at TeaCommerce.Umbraco.Web.TC.GetVariantGroups[T](Int64 storeId, T product, Boolean onlyValid) in C:\Users\niklas.raab\AppData\Local\JetBrains\Shared\v07\DecompilerCache\decompiler\2DBF3533-0880-4597-9E2C-62FFDD726AA9\ae\88000066\TC.cs:line 330
   at ASP._Page_Views_MacroPartials_List_Variants_of_Product_cshtml.Execute() in c:\Dev\PGM\trunk\.NET\Orca.Homepage.Web\Views\MacroPartials\List Variants of Product.cshtml:line 12
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at Umbraco.Web.Mvc.ControllerExtensions.RenderViewResultAsString(ControllerBase controller, ViewResultBase viewResult)
   at Umbraco.Web.Macros.PartialViewMacroEngine.Execute(MacroModel macro, IPublishedContent content)
   at Umbraco.Web.Macros.PartialViewMacroEngine.Execute(MacroModel macro, INode node)
   at umbraco.macro.LoadPartialViewMacro(MacroModel macro)
   at umbraco.macro.renderMacro(Hashtable pageElements, Int32 pageId)
   at Umbraco.Web.UmbracoComponentRenderer.RenderMacro(macro m, IDictionary`2 parameters, page umbracoPage)
   at Umbraco.Web.UmbracoComponentRenderer.RenderMacro(String alias, IDictionary`2 parameters, page umbracoPage)
   at Umbraco.Web.UmbracoComponentRenderer.RenderMacro(String alias, IDictionary`2 parameters)
   at Umbraco.Web.UmbracoHelper.RenderMacro(String alias, IDictionary`2 parameters)
   at ASP._Page_Views_Partials_grid_editors_macro_cshtml.Execute() in c:\Dev\PGM\trunk\.NET\Orca.Homepage.Web\Views\Partials\Grid\Editors\Macro.cshtml:line 13
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.HtmlHelper.RenderPartialInternal(String partialViewName, ViewDataDictionary viewData, Object model, TextWriter writer, ViewEngineCollection viewEngineCollection)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model)
   at ASP._Page_Views_Partials_grid_editors_base_cshtml.Execute() in c:\Dev\PGM\trunk\.NET\Orca.Homepage.Web\Views\Partials\Grid\Editors\Base.cshtml:line 19
```

What is  the problem? It occours only after the update

**Comment by NiklasRaab** [comment]
Found the Issue. I have to call something like this:
`TC.GetVariantGroups<IPublishedContent>(1, product);`

But please fix if i product is concret Type they throw above exception. I want to call: 
`TC.GetVariantGroups(1, product);`
Think this helps: https://blogs.msdn.microsoft.com/csharpfaq/2010/02/16/covariance-and-contravariance-faq/

And pleas add generic constrains for IPublishedContent

**Comment by andersburla** [comment]
Thanks for finding a solution. We will look into making the API even more easy to use
